### ISSUE TITLE
C64 ram report, and  downloadable releases

### ISSUE THREAD

**Issue by bozimmerman** [zeldin/super-reu#2]
First a small suggestion:
On the Releases page here, I would suggest posting whether the *.xz movies are 50hz or 60hz.  Unless I read the docs wrong, this is an important distinction.

Second, I'm curious why my C64s report 30719 bytes free with the Orange cartridge installed?

Last: Any recommendations on SD cards?  I'm using a "Samsung PRO Endurance 32GB 100MB/s (U1) MicroSDXC Memory Card", and get occasional errors from the orange cart.

Thanks!

**Comment by zeldin** [comment]
Hi Bo.
The movies are generated at 50hz, but the intention is that they should play at 60hz as well, only at a slightly too high speed.  This is why there is two fields for the samplerate.  However, I realize now that the code is always using the 50hz value, even on an NTSC C64, which is a bug.  Thanks for reminding me.  I don't have any NTSC machines to test with, so any feedback here would be appreciated.
The 30719 bytes is because of the ROM at $8000-$9fff which contains the movie player.  BASIC will avoid using RAM areas covered by ROM.  The ROM is actually disabled when entering BASIC, but it looks like the memory check might happen before that.  I need to double check.
I haven't done any extensive testing of different SD cards, but the one I'm using is a Kingston SDHC UHS-I card which has always worked fine.  Do note that you may get an error when inserting the card that does not indicate a problem with the card itself, but rather that the application does not wait long enough between card detect and accessing the card.  The point at which the card is detected seems to vary a little between individual units, so I've been meaning to increase the delay to compensate for that.  You can try inserting the card before entering the file selector.
Hm, now this turned out as a single issue for three different things to fix, but I guess I'll manage.  :smile:

**Comment by bozimmerman** [comment]
Thank you!
